[daemonize]
# log_to = "syslog" or /file/path
log_to = "syslog"
pid_file = "/run/illuminanced.pid"
# log_level = "OFF", "ERROR", "WARN", "INFO", "DEBUG", "TRACE"
log_level = "ERROR"

[general]
check_period_in_seconds = 1
light_steps = 10
min_backlight = 70
step_barrier = 0.0
max_backlight_file = "/sys/class/backlight/amdgpu_bl1/max_brightness"
backlight_file = "/sys/class/backlight/amdgpu_bl1/brightness"
illuminance_file = "/sys/bus/iio/devices/iio:device0/in_illuminance_raw"
event_device_mask = "/dev/input/event*"
# use `sudo evtest` to see devices and provided keycodes in hex
event_device_name = "Asus WMI hotkeys"
enable_max_brightness_mode = true
filename_for_sensor_activation = ""
# use `sudo showkey` to find the key code
# use 0xXXX for hex value
switch_key_code = 560 #  KEY_ALS_TOGGLE

[kalman]
q = 1
r = 20
covariance = 10

[light]
points_count = 8

illuminance_0 = 0
light_0 = 3

illuminance_1 = 20
light_1 = 4

illuminance_2 = 100
light_2 = 5

illuminance_3 = 300
light_3 = 6

illuminance_4 = 700
light_4 = 7

illuminance_5 = 1500
light_5 = 8

illuminance_6 = 4000
light_6 = 9

illuminance_7 = 10000
light_7 = 10

