# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
    ./disk-sleep.nix
    ./zfs.nix
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/7fb04574-9098-4a19-a8d6-098beed657e1";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/36E5-4978";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/mnt/eye" = {
    device = "eye";
    fsType = "zfs";
  };

  fileSystems."/mnt/eye/documents" = {
    device = "eye/documents";
    fsType = "zfs";
  };

  fileSystems."/mnt/eye/downloads" = {
    device = "eye/downloads";
    fsType = "zfs";
  };

  fileSystems."/mnt/eye/movies" = {
    device = "eye/movies";
    fsType = "zfs";
  };

  fileSystems."/mnt/eye/music" = {
    device = "eye/music";
    fsType = "zfs";
  };

  fileSystems."/mnt/eye/pictures" = {
    device = "eye/pictures";
    fsType = "zfs";
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/30b26b23-04fd-4645-b72a-da5c240c030e";}
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
