# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."twenty-db" = {
    image = "postgres:16";
    environment = {
      "POSTGRES_DB" = "default";
      "POSTGRES_PASSWORD" = "postgres";
      "POSTGRES_USER" = "postgres";
    };
    volumes = [
      "twenty_db-data:/var/lib/postgresql/data:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=pg_isready -U postgres -h localhost -d postgres"
      "--health-interval=5s"
      "--health-retries=10"
      "--health-timeout=5s"
      "--network-alias=db"
      "--network=twenty_default"
    ];
  };
  systemd.services."podman-twenty-db" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-twenty_default.service"
      "podman-volume-twenty_db-data.service"
    ];
    requires = [
      "podman-network-twenty_default.service"
      "podman-volume-twenty_db-data.service"
    ];
    partOf = [
      "podman-compose-twenty-root.target"
    ];
    wantedBy = [
      "podman-compose-twenty-root.target"
    ];
  };
  virtualisation.oci-containers.containers."twenty-redis" = {
    image = "redis";
    cmd = [ "--maxmemory-policy" "noeviction" ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=[\"redis-cli\", \"ping\"]"
      "--health-interval=5s"
      "--health-retries=10"
      "--health-timeout=5s"
      "--network-alias=redis"
      "--network=twenty_default"
    ];
  };
  systemd.services."podman-twenty-redis" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-twenty_default.service"
    ];
    requires = [
      "podman-network-twenty_default.service"
    ];
    partOf = [
      "podman-compose-twenty-root.target"
    ];
    wantedBy = [
      "podman-compose-twenty-root.target"
    ];
  };
  virtualisation.oci-containers.containers."twenty-server" = {
    image = "twentycrm/twenty:latest";
    environment = {
      "APP_SECRET" = "replace_me_with_a_random_string";
      "DISABLE_CRON_JOBS_REGISTRATION" = "";
      "DISABLE_DB_MIGRATIONS" = "";
      "NODE_PORT" = "3000";
      "PG_DATABASE_URL" = "postgres://postgres:postgres@db:5432/default";
      "REDIS_URL" = "redis://redis:6379";
      "SERVER_URL" = "";
      "STORAGE_S3_ENDPOINT" = "";
      "STORAGE_S3_NAME" = "";
      "STORAGE_S3_REGION" = "";
      "STORAGE_TYPE" = "";
    };
    volumes = [
      "twenty_server-local-data:/app/packages/twenty-server/.local-storage:rw"
    ];
    ports = [
      "3000:3000/tcp"
    ];
    dependsOn = [
      "twenty-db"
      "twenty-redis"
    ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=curl --fail http://localhost:3000/healthz"
      "--health-interval=5s"
      "--health-retries=20"
      "--health-timeout=5s"
      "--network-alias=server"
      "--network=twenty_default"
    ];
  };
  systemd.services."podman-twenty-server" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-twenty_default.service"
      "podman-volume-twenty_server-local-data.service"
    ];
    requires = [
      "podman-network-twenty_default.service"
      "podman-volume-twenty_server-local-data.service"
    ];
    partOf = [
      "podman-compose-twenty-root.target"
    ];
    wantedBy = [
      "podman-compose-twenty-root.target"
    ];
  };
  virtualisation.oci-containers.containers."twenty-worker" = {
    image = "twentycrm/twenty:latest";
    environment = {
      "APP_SECRET" = "replace_me_with_a_random_string";
      "DISABLE_CRON_JOBS_REGISTRATION" = "true";
      "DISABLE_DB_MIGRATIONS" = "true";
      "PG_DATABASE_URL" = "postgres://postgres:postgres@db:5432/default";
      "REDIS_URL" = "redis://redis:6379";
      "SERVER_URL" = "";
      "STORAGE_S3_ENDPOINT" = "";
      "STORAGE_S3_NAME" = "";
      "STORAGE_S3_REGION" = "";
      "STORAGE_TYPE" = "";
    };
    volumes = [
      "twenty_server-local-data:/app/packages/twenty-server/.local-storage:rw"
    ];
    cmd = [ "yarn" "worker:prod" ];
    dependsOn = [
      "twenty-db"
      "twenty-server"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=worker"
      "--network=twenty_default"
    ];
  };
  systemd.services."podman-twenty-worker" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-twenty_default.service"
      "podman-volume-twenty_server-local-data.service"
    ];
    requires = [
      "podman-network-twenty_default.service"
      "podman-volume-twenty_server-local-data.service"
    ];
    partOf = [
      "podman-compose-twenty-root.target"
    ];
    wantedBy = [
      "podman-compose-twenty-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-twenty_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f twenty_default";
    };
    script = ''
      podman network inspect twenty_default || podman network create twenty_default
    '';
    partOf = [ "podman-compose-twenty-root.target" ];
    wantedBy = [ "podman-compose-twenty-root.target" ];
  };

  # Volumes
  systemd.services."podman-volume-twenty_db-data" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect twenty_db-data || podman volume create twenty_db-data
    '';
    partOf = [ "podman-compose-twenty-root.target" ];
    wantedBy = [ "podman-compose-twenty-root.target" ];
  };
  systemd.services."podman-volume-twenty_server-local-data" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect twenty_server-local-data || podman volume create twenty_server-local-data
    '';
    partOf = [ "podman-compose-twenty-root.target" ];
    wantedBy = [ "podman-compose-twenty-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-twenty-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
