keys:
  - &primary age120vyha395746f30z5s38rzhmnngkcm3ghlp8rxhw90ew7vjum3rqjpys0n
  - &earth age1lqr9sh8vrnady7rx249aw6gpsq5cjawdyd6u3gjlh6vwd7kxweaslz5y7g
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
      - age:
          - *primary
          - *earth
