keys:
  - &hosts:
    - &earth age1lqr9sh8vrnady7rx249aw6gpsq5cjawdyd6u3gjlh6vwd7kxweaslz5y7g
    - &jupiter  age1r3nky8g3jr37ne3dmm6050m9g5s0yvz6ly9xahfuhgpwdld5x5zsv3z795
    - &mars age120vyha395746f30z5s38rzhmnngkcm3ghlp8rxhw90ew7vjum3rqjpys0n
creation_rules:
  - path_regex: secrets\.yaml$
    key_groups:
      - age:
        - *earth
        - *jupiter
        - *mars
